---
output:
  html_document:
    keep_md: yes
    toc: no
    self_contained: no
  pdf_document:
    toc: yes
---

# README

Materials for the evaluation of restoration projects using Bayes Decision Networks.

# Content

Evaluation of simple model, all time periods: [link](https://fawda123.github.io/restorebayes/obs_eval) 

Evaluation of simple model, randomizations: [link](https://fawda123.github.io/restorebayes/rnd_eval)

Evaluation of simple model, pre/post 1994: [link](https://fawda123.github.io/restorebayes/sub_eval)

Evaluation of simple model, restoration project types: [link](https://fawda123.github.io/restorebayes/typ_eval)

Evaluation of complete model, restoration project types: [link](https://fawda123.github.io/restorebayes/all_eval)

Evaluation of complete model, restoratoin project types, pre/post 1994: [link](https://fawda123.github.io/restorebayes/allsub_eval)

# From Ed

As was mentioned, I think the approach of subsetting the data by TRT and time may make the most sense in terms of what hypotheses/modeling techniques we’re trying to develop to inform other restoration activities. So, reframing some of the thoughts thus far, below are the basic tenets I think we’re trying to establish in our modeling/analysis framework :

Ho1:       Do softer restoration techniques (e.g. habitat creation, etc.) produce similar improvements in WQ conditions in comparison to harder-infrastructure restoration techniques (e.g. stromwater BMPs, etc.)? 

Ho2:       Will implementing either (or both) of these techniques significantly improve WQ conditions in comparison to doing nothing at all (I think this is where we create value in utilizing the TB datasets in developing expected outcomes for other regions)? 

Ho3:       If the restoration techniques have inherent WQ improvement benefits (as developed in TB), to what degree are benefits accumulated through time?

Ultimate Goal: Can we utilize the evidence garnered from the questions above to assign a probabilistic expectation for WQ benefits derived from certain restoration activity investments?

